-- V1: 초기 스키마 (O-1). Hibernate 스키마 생성(ddl-auto: create) 시절의 최종 형태를
-- PostgreSQL 방언으로 덤프한 뒤 손 감사한 결과다.
--
-- 덤프 대비 달라진 것:
--   * FK·check 제약에 이름 부여 (OI-16) — 해시 이름은 에러 메시지에서 읽을 수 없다
--   * cover_image의 unique에 이름 복원 — 엔티티에는 있었는데 Hibernate가 인라인으로 뭉갰다
--   * game.summary/storyline → text (OI-15) — varchar(32600)으로 나오던 것을 엔티티와 함께 교정
--   * FK 컬럼 인덱스 명시 — H2는 FK에 인덱스를 자동 생성하지만 PostgreSQL은 안 한다.
--     이미 유니크·인덱스의 선두 컬럼인 FK는 제외
--
-- H2(MODE=PostgreSQL)와 PostgreSQL 양쪽에서 도는 문법만 쓴다.

-- ============ 회원 ============

create table member (
    id              bigint generated by default as identity primary key,
    email           varchar(320) not null,
    nickname        varchar(30)  not null,
    password        varchar(100),
    google_subject  varchar(100),
    role            varchar(20)  not null,
    email_verified  boolean      not null,
    memo            text,
    deleted_at      timestamp(6),
    created_at      timestamp(6),
    updated_at      timestamp(6),
    constraint uk_member_email unique (email),
    constraint uk_member_google_subject unique (google_subject),
    constraint chk_member_role check (role in ('USER','ADMIN'))
);

create index idx_member_deleted_at on member (deleted_at);

create table auth_token (
    id          bigint generated by default as identity primary key,
    member_id   bigint       not null,
    purpose     varchar(30)  not null,
    token_hash  varchar(100) not null,
    expires_at  timestamp(6) not null,
    used_at     timestamp(6),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    constraint uk_auth_token_hash unique (token_hash),
    constraint chk_auth_token_purpose check (purpose in ('EMAIL_VERIFICATION','PASSWORD_RESET')),
    constraint fk_auth_token_member foreign key (member_id) references member (id)
);

create index idx_auth_token_expires_at on auth_token (expires_at);
create index idx_auth_token_member on auth_token (member_id);

create table audit_log (
    id          bigint generated by default as identity primary key,
    actor_id    bigint      not null,
    action      varchar(50) not null,
    target_type varchar(50),
    target_id   bigint,
    request_ip  varchar(50),
    user_agent  varchar(500),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    constraint fk_audit_log_actor foreign key (actor_id) references member (id)
);

create index idx_audit_log_actor on audit_log (actor_id);

-- ============ 게임 마스터 ============

create table game (
    id                   bigint generated by default as identity primary key,
    source               varchar(20)  not null,
    external_id          varchar(50),
    name                 varchar(300) not null,
    summary              text,
    storyline            text,
    released_on          date,
    cover_image_id       varchar(50),
    banner_image_id      varchar(50),
    igdb_rating          numeric(5,2),
    igdb_rating_count    integer,
    main_story_hours     integer,
    main_extra_hours     integer,
    completionist_hours  integer,
    time_to_beat_samples integer,
    list_price_amount    numeric(19,2),
    list_price_currency  varchar(3),
    last_synced_at       timestamp(6),
    created_at           timestamp(6),
    updated_at           timestamp(6),
    constraint uk_game_source_external_id unique (source, external_id),
    constraint chk_game_source check (source in ('IGDB','MANUAL'))
);

create table game_developer (
    game_id   bigint not null,
    developer varchar(200),
    constraint fk_game_developer_game foreign key (game_id) references game (id)
);

create index idx_game_developer_game on game_developer (game_id);

create table game_publisher (
    game_id   bigint not null,
    publisher varchar(200),
    constraint fk_game_publisher_game foreign key (game_id) references game (id)
);

create index idx_game_publisher_game on game_publisher (game_id);

create table game_master_genre (
    game_id bigint not null,
    genre   varchar(100),
    constraint fk_game_master_genre_game foreign key (game_id) references game (id)
);

create index idx_game_master_genre_game on game_master_genre (game_id);

create table game_release_platform (
    game_id       bigint not null,
    platform_name varchar(100),
    constraint fk_game_release_platform_game foreign key (game_id) references game (id)
);

create index idx_game_release_platform_game on game_release_platform (game_id);

-- ============ 플랫폼·기기 ============

create table platform (
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_platform_name unique (name)
);

create table device (
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_device_name unique (name)
);

create table emulator (
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_emulator_name unique (name)
);

create table platform_account (
    id            bigint generated by default as identity primary key,
    member_id     bigint      not null,
    platform_id   bigint      not null,
    account_label varchar(50) not null,
    deleted_at    timestamp(6),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    constraint uk_platform_account unique (member_id, platform_id, account_label),
    constraint fk_platform_account_member foreign key (member_id) references member (id),
    constraint fk_platform_account_platform foreign key (platform_id) references platform (id)
);

create index idx_platform_account_platform on platform_account (platform_id);

create table member_device (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    device_id  bigint      not null,
    label      varchar(50) not null,
    memo       text,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_member_device unique (member_id, device_id, label),
    constraint fk_member_device_member foreign key (member_id) references member (id),
    constraint fk_member_device_device foreign key (device_id) references device (id)
);

create index idx_member_device_device on member_device (device_id);

-- ============ 구독 ============

create table subscription (
    id            bigint generated by default as identity primary key,
    member_id     bigint       not null,
    service_name  varchar(100) not null,
    billing_cycle varchar(20)  not null,
    fee_amount    numeric(19,2),
    fee_currency  varchar(3),
    started_on    date         not null,
    ended_on      date,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    constraint chk_subscription_billing_cycle check (billing_cycle in ('MONTHLY','YEARLY')),
    constraint fk_subscription_member foreign key (member_id) references member (id)
);

create index idx_subscription_member on subscription (member_id);

-- ============ 태그·장르 ============

create table tag (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_tag_member_name unique (member_id, name),
    constraint fk_tag_member foreign key (member_id) references member (id)
);

create table genre (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_genre_member_name unique (member_id, name),
    constraint fk_genre_member foreign key (member_id) references member (id)
);

-- ============ 백로그 ============

create table backlog_entry (
    id                           bigint generated by default as identity primary key,
    member_id                    bigint       not null,
    game_id                      bigint       not null,
    status                       varchar(20)  not null,
    display_name                 varchar(300) not null,
    name_override                varchar(300),
    released_on_override         date,
    released_on_resolved         date,
    list_price_override_amount   numeric(19,2),
    list_price_override_currency varchar(3),
    rating                       numeric(4,1),
    play_time_hours              integer,
    last_played_on               date,
    last_playthrough_id          bigint,
    memo                         text,
    deleted_at                   timestamp(6),
    created_at                   timestamp(6),
    updated_at                   timestamp(6),
    constraint uk_backlog_entry_member_game unique (member_id, game_id),
    constraint chk_backlog_entry_status check (status in ('WISHLIST','BACKLOG','PLAYING','PAUSED','DROPPED','COMPLETED')),
    constraint fk_backlog_entry_member foreign key (member_id) references member (id),
    constraint fk_backlog_entry_game foreign key (game_id) references game (id)
);

create index idx_backlog_member_status on backlog_entry (member_id, status);
create index idx_backlog_member_last_played on backlog_entry (member_id, last_played_on);
create index idx_backlog_member_display_name on backlog_entry (member_id, display_name);
create index idx_backlog_member_released_on on backlog_entry (member_id, released_on_resolved);
create index idx_backlog_entry_game on backlog_entry (game_id);
create index idx_backlog_entry_last_playthrough on backlog_entry (last_playthrough_id);

create table backlog_developer_override (
    backlog_entry_id bigint not null,
    developer        varchar(200),
    constraint fk_backlog_developer_override_entry foreign key (backlog_entry_id) references backlog_entry (id)
);

create index idx_backlog_developer_override_entry on backlog_developer_override (backlog_entry_id);

create table backlog_publisher_override (
    backlog_entry_id bigint not null,
    publisher        varchar(200),
    constraint fk_backlog_publisher_override_entry foreign key (backlog_entry_id) references backlog_entry (id)
);

create index idx_backlog_publisher_override_entry on backlog_publisher_override (backlog_entry_id);

create table backlog_entry_tag (
    id               bigint generated by default as identity primary key,
    backlog_entry_id bigint not null,
    tag_id           bigint not null,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    constraint uk_backlog_entry_tag unique (backlog_entry_id, tag_id),
    constraint fk_backlog_entry_tag_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_backlog_entry_tag_tag foreign key (tag_id) references tag (id)
);

create index idx_backlog_entry_tag_tag on backlog_entry_tag (tag_id);

create table backlog_entry_genre (
    id               bigint generated by default as identity primary key,
    backlog_entry_id bigint not null,
    genre_id         bigint not null,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    constraint uk_backlog_entry_genre unique (backlog_entry_id, genre_id),
    constraint fk_backlog_entry_genre_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_backlog_entry_genre_genre foreign key (genre_id) references genre (id)
);

create index idx_backlog_entry_genre_genre on backlog_entry_genre (genre_id);

create table playthrough (
    id                  bigint generated by default as identity primary key,
    backlog_entry_id    bigint      not null,
    sequence_no         integer     not null,
    status              varchar(20) not null,
    label               varchar(100),
    started_on          date        not null,
    finished_on         date,
    platform_account_id bigint,
    device_id           bigint,
    emulator_id         bigint,
    input_method        varchar(20),
    created_at          timestamp(6),
    updated_at          timestamp(6),
    constraint uk_playthrough_sequence unique (backlog_entry_id, sequence_no),
    constraint chk_playthrough_status check (status in ('PLAYING','PAUSED','DROPPED','COMPLETED')),
    constraint chk_playthrough_input_method check (input_method in ('XINPUT','NINTENDO','PLAYSTATION','KEYBOARD_MOUSE')),
    constraint fk_playthrough_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_playthrough_platform_account foreign key (platform_account_id) references platform_account (id),
    constraint fk_playthrough_device foreign key (device_id) references device (id),
    constraint fk_playthrough_emulator foreign key (emulator_id) references emulator (id)
);

create index idx_playthrough_platform_account on playthrough (platform_account_id);
create index idx_playthrough_device on playthrough (device_id);
create index idx_playthrough_emulator on playthrough (emulator_id);

-- backlog_entry.last_playthrough_id → playthrough는 상호 참조라 여기서 건다
alter table backlog_entry
    add constraint fk_backlog_entry_last_playthrough foreign key (last_playthrough_id) references playthrough (id);

create table acquisition (
    id                  bigint generated by default as identity primary key,
    backlog_entry_id    bigint      not null,
    method              varchar(20) not null,
    label               varchar(100),
    price_amount        numeric(19,2),
    price_currency      varchar(3),
    acquired_on         date,
    platform_id         bigint,
    platform_account_id bigint,
    subscription_id     bigint,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    constraint chk_acquisition_method check (method in ('PURCHASED','SUBSCRIPTION','FREE','GIFT','BORROWED','DEMO','NOT_OWNED')),
    constraint fk_acquisition_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_acquisition_platform foreign key (platform_id) references platform (id),
    constraint fk_acquisition_platform_account foreign key (platform_account_id) references platform_account (id),
    constraint fk_acquisition_subscription foreign key (subscription_id) references subscription (id)
);

create index idx_acquisition_entry on acquisition (backlog_entry_id);
create index idx_acquisition_platform on acquisition (platform_id);
create index idx_acquisition_platform_account on acquisition (platform_account_id);
create index idx_acquisition_subscription on acquisition (subscription_id);

create table cover_image (
    id               bigint generated by default as identity primary key,
    backlog_entry_id bigint       not null,
    storage_key      varchar(300) not null,
    content_type     varchar(100) not null,
    size_bytes       bigint       not null,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    constraint uk_cover_image_backlog_entry unique (backlog_entry_id),
    constraint fk_cover_image_entry foreign key (backlog_entry_id) references backlog_entry (id)
);

create table entity_snapshot (
    id          bigint generated by default as identity primary key,
    target_type varchar(20) not null,
    target_id   bigint      not null,
    changed_by  bigint      not null,
    payload     text        not null,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    constraint chk_entity_snapshot_target_type check (target_type in ('BACKLOG_ENTRY','PLAYTHROUGH')),
    constraint fk_entity_snapshot_member foreign key (changed_by) references member (id)
);

create index idx_snapshot_target on entity_snapshot (target_type, target_id, created_at);
create index idx_entity_snapshot_changed_by on entity_snapshot (changed_by);
