-- V1: 스키마 베이스라인 (Phase 9 재작성, 2026-08-26).
--
-- 원래 V1(Hibernate 덤프 감사본) → V2(선택지 회원 소유 전환) → V3(가입 승인제)의
-- 3단 역사를 **하나로 청산한 판이다.** 첫 실배포 전 + 데이터가 소모품인 시점이라
-- 마이그레이션 역사를 유지할 이유가 없었다 — 새 환경마다 "member_device를 만들었다
-- 지우는" 가짜 역사를 재생하는 비용만 남는다. 옛 판은 git 이력에 있다.
--
-- 손으로 쓴 이유 — Hibernate 생성 DDL은 인덱스가 없고 제약 이름이 해시라
-- 에러 메시지에서 읽을 수 없다 (OI-16). 인덱스는 전부 실제 쿼리 경로가 근거다.
-- 근거 없는 인덱스는 두지 않았다 — 각 인덱스 옆 주석이 그 근거다.
--
-- FK 컬럼 인덱스 정책 — H2는 FK에 인덱스를 자동으로 만들지만 PostgreSQL은 안 만든다.
-- 조회·삭제 경로가 실재하는 FK만 명시적 인덱스를 건다. 유니크 제약의 선두 컬럼이면 생략
-- (유니크 인덱스의 접두어로 충분하다).
--
-- H2(MODE=PostgreSQL, dev)와 PostgreSQL(prod) 양쪽에서 도는 문법만 쓴다.
-- 부분 인덱스(where deleted_at is null)는 H2가 지원하지 않아 쓰지 않는다.

-- ============ 회원 ============

create table member (
    id              bigint generated by default as identity primary key,
    email           varchar(320) not null,
    nickname        varchar(30)  not null,
    password        varchar(100),                 -- null = 구글 전용 계정 (FR-AUTH-12)
    google_subject  varchar(100),
    role            varchar(20)  not null,
    email_verified  boolean      not null,
    approved_at     timestamp(6),                 -- null = 승인 대기 (FR-ADM-06)
    memo            text,
    deleted_at      timestamp(6),                 -- 탈퇴 유예 (FR-AUTH-09)
    created_at      timestamp(6),
    updated_at      timestamp(6),
    constraint uk_member_email unique (email),
    constraint uk_member_google_subject unique (google_subject),
    constraint chk_member_role check (role in ('USER','ADMIN'))
);

-- 유예 만료 물리 삭제 배치가 deleted_at < threshold로 훑는다 (FR-SYS-06)
create index idx_member_deleted_at on member (deleted_at);
-- approved_at 인덱스는 두지 않는다 — 승인제 자체가 회원 수를 강제로 작게 유지하고,
-- 대기 목록 조회는 전체 스캔으로 충분하다. 단독 필터 경로도 없다

create table auth_token (
    id          bigint generated by default as identity primary key,
    member_id   bigint       not null,
    purpose     varchar(30)  not null,
    token_hash  varchar(100) not null,
    expires_at  timestamp(6) not null,
    used_at     timestamp(6),                     -- null = 미사용
    created_at  timestamp(6),
    updated_at  timestamp(6),
    constraint uk_auth_token_hash unique (token_hash),
    constraint chk_auth_token_purpose check (purpose in ('EMAIL_VERIFICATION','PASSWORD_RESET')),
    constraint fk_auth_token_member foreign key (member_id) references member (id)
);

-- 정리 배치가 만료·사용분을 expires_at으로 지운다 (04:30 크론)
create index idx_auth_token_expires_at on auth_token (expires_at);
-- 회원 탈퇴 물리 삭제가 member_id로 지운다
create index idx_auth_token_member on auth_token (member_id);

create table audit_log (
    id          bigint generated by default as identity primary key,
    actor_id    bigint      not null,
    action      varchar(50) not null,
    target_type varchar(50),
    target_id   bigint,
    request_ip  varchar(50),
    user_agent  varchar(500),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    constraint fk_audit_log_actor foreign key (actor_id) references member (id)
);

-- 회원 탈퇴 물리 삭제 경로
create index idx_audit_log_actor on audit_log (actor_id);
-- 보존 기간(1년, OI-08) 만료 삭제 배치가 created_at < threshold로 훑는다.
-- 옛 V1에 없던 인덱스다 — 로그는 단조 증가라 이 배치가 유일하게 전체를 훑는 경로였다
create index idx_audit_log_created_at on audit_log (created_at);

-- ============ 게임 마스터 (전 회원 공유, 관리자만 수정) ============

create table game (
    id                   bigint generated by default as identity primary key,
    source               varchar(20)  not null,
    external_id          varchar(50),             -- MANUAL이면 null. PG는 null끼리 중복 허용
    name                 varchar(300) not null,
    summary              text,
    storyline            text,
    released_on          date,
    cover_image_id       varchar(50),
    banner_image_id      varchar(50),
    igdb_rating          numeric(5,2),
    igdb_rating_count    integer,
    main_story_hours     integer,
    main_extra_hours     integer,
    completionist_hours  integer,
    time_to_beat_samples integer,
    list_price_amount    numeric(19,2),
    list_price_currency  varchar(3),
    last_synced_at       timestamp(6),
    created_at           timestamp(6),
    updated_at           timestamp(6),
    constraint uk_game_source_external_id unique (source, external_id),
    constraint chk_game_source check (source in ('IGDB','MANUAL'))
);
-- 이름 검색은 like '%…%'라 btree를 못 탄다. 마스터가 커지면 trigram(PG 전용)을 검토한다

create table game_developer (
    game_id   bigint not null,
    developer varchar(200),
    constraint fk_game_developer_game foreign key (game_id) references game (id)
);
create index idx_game_developer_game on game_developer (game_id);

create table game_publisher (
    game_id   bigint not null,
    publisher varchar(200),
    constraint fk_game_publisher_game foreign key (game_id) references game (id)
);
create index idx_game_publisher_game on game_publisher (game_id);

create table game_master_genre (
    game_id bigint not null,
    genre   varchar(100),
    constraint fk_game_master_genre_game foreign key (game_id) references game (id)
);
create index idx_game_master_genre_game on game_master_genre (game_id);

-- IGDB가 주는 "이 게임이 나온 플랫폼" 문자열. 회원 소유 platform과는 무관한 마스터 정보다
create table game_release_platform (
    game_id       bigint not null,
    platform_name varchar(100),
    constraint fk_game_release_platform_game foreign key (game_id) references game (id)
);
create index idx_game_release_platform_game on game_release_platform (game_id);

-- ============ 선택지 5종 (회원 소유, 소프트 삭제 — §7.4) ============
-- 회차·취득이 참조하므로 물리 삭제하지 않는다. deleted_at으로 선택지에서만 뺀다.
-- unique의 선두가 member_id라 회원별 목록 조회는 이 인덱스의 접두어를 탄다

create table platform (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    deleted_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_platform unique (member_id, name),
    constraint fk_platform_member foreign key (member_id) references member (id)
);

create table device (
    id          bigint generated by default as identity primary key,
    member_id   bigint      not null,
    device_type varchar(50) not null,             -- "Windows PC" — 기종. 직접 입력
    label       varchar(50) not null,             -- "거실 스위치" — 정체성. 유니크의 주체
    memo        text,                             -- 스펙·주의점. 마크다운
    deleted_at  timestamp(6),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    constraint uk_device unique (member_id, label),
    constraint fk_device_member foreign key (member_id) references member (id)
);

create table emulator (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    memo       text,
    deleted_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_emulator unique (member_id, name),
    constraint fk_emulator_member foreign key (member_id) references member (id)
);

create table input_method (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    deleted_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_input_method unique (member_id, name),
    constraint fk_input_method_member foreign key (member_id) references member (id)
);

create table platform_account (
    id            bigint generated by default as identity primary key,
    member_id     bigint      not null,
    platform_id   bigint      not null,
    account_label varchar(50) not null,
    deleted_at    timestamp(6),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    constraint uk_platform_account unique (member_id, platform_id, account_label),
    constraint fk_platform_account_member foreign key (member_id) references member (id),
    constraint fk_platform_account_platform foreign key (platform_id) references platform (id)
);

-- 플랫폼 소프트 삭제가 딸린 계정을 platform_id로 찾아 함께 닫는다 (§6.5)
create index idx_platform_account_platform on platform_account (platform_id);

-- ============ 구독 ============

create table subscription (
    id            bigint generated by default as identity primary key,
    member_id     bigint       not null,
    service_name  varchar(100) not null,
    billing_cycle varchar(20)  not null,
    fee_amount    numeric(19,2),
    fee_currency  varchar(3),
    started_on    date         not null,
    ended_on      date,                           -- null = 구독 중
    created_at    timestamp(6),
    updated_at    timestamp(6),
    constraint chk_subscription_billing_cycle check (billing_cycle in ('MONTHLY','YEARLY')),
    constraint fk_subscription_member foreign key (member_id) references member (id)
);

-- 회원별 목록 조회 (유니크가 없어 별도 인덱스)
create index idx_subscription_member on subscription (member_id);

-- ============ 태그·장르 사전 (회원 소유 — §6.7 자동 소멸) ============

create table tag (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_tag_member_name unique (member_id, name),
    constraint fk_tag_member foreign key (member_id) references member (id)
);

create table genre (
    id         bigint generated by default as identity primary key,
    member_id  bigint      not null,
    name       varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_genre_member_name unique (member_id, name),
    constraint fk_genre_member foreign key (member_id) references member (id)
);

-- ============ 백로그 ============

create table backlog_entry (
    id                           bigint generated by default as identity primary key,
    member_id                    bigint       not null,
    game_id                      bigint       not null,
    status                       varchar(20)  not null,
    display_name                 varchar(300) not null,  -- 오버라이드 반영 비정규화 (§7.2)
    name_override                varchar(300),
    released_on_override         date,
    released_on_resolved         date,                   -- COALESCE(override, master) 비정규화
    list_price_override_amount   numeric(19,2),
    list_price_override_currency varchar(3),
    rating                       numeric(4,1),           -- 0.0 ~ 100.0
    play_time_hours              integer,
    last_played_on               date,
    last_playthrough_id          bigint,                 -- 최신 회차 비정규화 (§7.6)
    memo                         text,
    deleted_at                   timestamp(6),           -- 소프트 삭제 + 되살리기 (§7.4)
    created_at                   timestamp(6),
    updated_at                   timestamp(6),
    constraint uk_backlog_entry_member_game unique (member_id, game_id),
    constraint chk_backlog_entry_status check (status in ('WISHLIST','BACKLOG','PLAYING','PAUSED','DROPPED','COMPLETED')),
    constraint fk_backlog_entry_member foreign key (member_id) references member (id),
    constraint fk_backlog_entry_game foreign key (game_id) references game (id)
);

-- 목록 정렬 4경로와 1:1 대응 (상태 필터 / 최근 플레이 / 이름순 / 출시일순)
create index idx_backlog_member_status on backlog_entry (member_id, status);
create index idx_backlog_member_last_played on backlog_entry (member_id, last_played_on);
create index idx_backlog_member_display_name on backlog_entry (member_id, display_name);
create index idx_backlog_member_released_on on backlog_entry (member_id, released_on_resolved);
-- 관리자 병합이 game_id로 항목을 옮긴다 (FR-ADM-02)
create index idx_backlog_entry_game on backlog_entry (game_id);
-- 회차 삭제 시 이 회차를 비정규화로 문 항목을 찾는다
create index idx_backlog_entry_last_playthrough on backlog_entry (last_playthrough_id);

create table backlog_developer_override (
    backlog_entry_id bigint not null,
    developer        varchar(200),
    constraint fk_backlog_developer_override_entry foreign key (backlog_entry_id) references backlog_entry (id)
);
create index idx_backlog_developer_override_entry on backlog_developer_override (backlog_entry_id);

create table backlog_publisher_override (
    backlog_entry_id bigint not null,
    publisher        varchar(200),
    constraint fk_backlog_publisher_override_entry foreign key (backlog_entry_id) references backlog_entry (id)
);
create index idx_backlog_publisher_override_entry on backlog_publisher_override (backlog_entry_id);

create table backlog_entry_tag (
    id               bigint generated by default as identity primary key,
    backlog_entry_id bigint not null,
    tag_id           bigint not null,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    constraint uk_backlog_entry_tag unique (backlog_entry_id, tag_id),
    constraint fk_backlog_entry_tag_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_backlog_entry_tag_tag foreign key (tag_id) references tag (id)
);
-- 태그 파셋 집계·태그 삭제 전파가 tag_id로 훑는다 (FR-TAG-02)
create index idx_backlog_entry_tag_tag on backlog_entry_tag (tag_id);

create table backlog_entry_genre (
    id               bigint generated by default as identity primary key,
    backlog_entry_id bigint not null,
    genre_id         bigint not null,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    constraint uk_backlog_entry_genre unique (backlog_entry_id, genre_id),
    constraint fk_backlog_entry_genre_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_backlog_entry_genre_genre foreign key (genre_id) references genre (id)
);
create index idx_backlog_entry_genre_genre on backlog_entry_genre (genre_id);

create table playthrough (
    id                  bigint generated by default as identity primary key,
    backlog_entry_id    bigint      not null,
    sequence_no         integer     not null,
    status              varchar(20) not null,
    label               varchar(100),
    started_on          date        not null,
    finished_on         date,                     -- null = 진행 중 (BR-PT-03의 판정 기준)
    platform_account_id bigint,
    device_id           bigint,
    emulator_id         bigint,
    input_method_id     bigint,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    constraint uk_playthrough_sequence unique (backlog_entry_id, sequence_no),
    constraint chk_playthrough_status check (status in ('PLAYING','PAUSED','DROPPED','COMPLETED')),
    constraint fk_playthrough_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_playthrough_platform_account foreign key (platform_account_id) references platform_account (id),
    constraint fk_playthrough_device foreign key (device_id) references device (id),
    constraint fk_playthrough_emulator foreign key (emulator_id) references emulator (id),
    constraint fk_playthrough_input_method foreign key (input_method_id) references input_method (id)
);

-- 파셋 집계(기기별·계정별 항목 수)와 필터가 이 FK들로 그룹핑·조인한다 (H-4, FR-QRY-03)
create index idx_playthrough_platform_account on playthrough (platform_account_id);
create index idx_playthrough_device on playthrough (device_id);
create index idx_playthrough_emulator on playthrough (emulator_id);
create index idx_playthrough_input_method on playthrough (input_method_id);

-- backlog_entry.last_playthrough_id → playthrough는 상호 참조라 여기서 건다
alter table backlog_entry
    add constraint fk_backlog_entry_last_playthrough foreign key (last_playthrough_id) references playthrough (id);

create table acquisition (
    id                  bigint generated by default as identity primary key,
    backlog_entry_id    bigint      not null,
    method              varchar(20) not null,
    label               varchar(100),
    price_amount        numeric(19,2),
    price_currency      varchar(3),
    acquired_on         date,
    platform_id         bigint,
    platform_account_id bigint,
    subscription_id     bigint,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    constraint chk_acquisition_method check (method in ('PURCHASED','SUBSCRIPTION','FREE','GIFT','BORROWED','DEMO','NOT_OWNED')),
    constraint fk_acquisition_entry foreign key (backlog_entry_id) references backlog_entry (id),
    constraint fk_acquisition_platform foreign key (platform_id) references platform (id),
    constraint fk_acquisition_platform_account foreign key (platform_account_id) references platform_account (id),
    constraint fk_acquisition_subscription foreign key (subscription_id) references subscription (id)
);

-- 항목 상세가 backlog_entry_id로 묶어 읽는다
create index idx_acquisition_entry on acquisition (backlog_entry_id);
-- 파셋 집계(계정별)·지출 통계가 이 FK들을 탄다
create index idx_acquisition_platform on acquisition (platform_id);
create index idx_acquisition_platform_account on acquisition (platform_account_id);
create index idx_acquisition_subscription on acquisition (subscription_id);

create table cover_image (
    id               bigint generated by default as identity primary key,
    backlog_entry_id bigint       not null,
    storage_key      varchar(300) not null,
    content_type     varchar(100) not null,
    size_bytes       bigint       not null,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    constraint uk_cover_image_backlog_entry unique (backlog_entry_id),
    constraint fk_cover_image_entry foreign key (backlog_entry_id) references backlog_entry (id)
);

-- entity_snapshot(변경 이력, FR-BL-09)은 이 판에 없다 — 엔티티만 있고 접근 경로가
-- 없는 죽은 테이블이었다. SHOULD 항목이라 구현하는 날 마이그레이션으로 추가한다
