-- v1.0 6·7·8단계를 한 번에 (docs/v1.0-roadmap.md).
--
-- ⚠️ **쪼개지 않는다.** 세이브파일마다 스키마 버전이 갈리면 9단계의 자동 업그레이드가
-- 다뤄야 할 경우의 수가 그만큼 늘어난다. 컬럼 추가와 테이블 삭제를 한 버전에 몬다.
--
-- PostgreSQL 전용 문법을 쓰지 않는다 — 로컬 모드(H2 파일)와 클라우드 모드(PostgreSQL)가
-- **같은 마이그레이션 한 벌**을 탄다 (architecture §3).

-- ============ 6단계 · 커버가 자기 위치를 안다 ============

-- LOCAL = 데이터 루트의 covers/ 폴더, EXTERNAL = S3 호환 스토리지.
-- 기존 행은 전부 EXTERNAL이다 — 로컬 저장이라는 개념 자체가 지금 생겼다.
-- default를 붙여 기존 행을 채우고, **채운 뒤에 걷어낸다** —
-- 스프링이 값을 항상 명시하므로 DB 기본값이 남아 있으면 "안 정해도 되는 값"처럼 보인다.
alter table cover_image add column location varchar(20) default 'EXTERNAL' not null;
alter table cover_image alter column location drop default;

-- ============ 7단계 · 스크린샷 폴더 ============

-- IGDB 영문명에서 만든 slug (`hollow-knight`). 파일은 <데이터루트>/media/<slug>/ 에 있다.
-- **폴더 이름을 여기 저장하는 이유** — 게임 이름이 바뀌어도 폴더를 따라가지 않게 하려는 것이다.
-- 이름을 매번 다시 slug로 만들면 이름 수정 한 번에 스크린샷이 통째로 사라진 것처럼 보인다.
alter table game add column media_folder varchar(200);

-- ============ 8단계 · 정렬 키 ============

-- 영문 먼저(대소문자 무시), 그다음 한글. `0|8-bit adventures` 처럼 그룹 번호를 앞에 붙인다.
-- **DB 콜레이션에 안 맡긴다** — H2와 PostgreSQL이 다르고, 클라우드 DB는 사용자가 아무거나
-- 고르므로 더더욱 보장할 수 없다 (architecture §10-5).
alter table backlog_entry add column display_name_sort_key varchar(320);
create index idx_backlog_entry_sort_key on backlog_entry (display_name_sort_key);

-- ============ 8단계 · API 호출 기록 ============

-- 카운터가 아니라 행이다. 외부 API 한도는 "초당 4회", "월 X회"처럼 전부 기간당 횟수라
-- 누적 숫자 하나로는 한도에 가까운지 알 수 없다.
create table api_call_log (
    id         bigint generated by default as identity primary key,
    provider   varchar(20)  not null,
    operation  varchar(50)  not null,
    called_at  timestamp(6) not null,
    success    boolean      not null,
    created_at timestamp(6),
    updated_at timestamp(6)
);

-- 집계도 보존기간 삭제도 (provider, called_at)로 훑는다. 단조 증가라 이 인덱스가 유일한 경로다
create index idx_api_call_log_provider_called on api_call_log (provider, called_at);

-- ============ 8단계 · 사라지는 것들 ============

-- 감사 로그: 물어볼 상황이 없다. 한 설치 = 한 사람이라 "누가 했나"의 답이 늘 같다
drop table audit_log;

-- 일일 쿼터: 무료 티어를 여럿이 나눠 쓰던 장치다. 내 키를 내가 쓰는 데 한도를 걸 이유가 없다
drop table usage_quota;

-- 세션: v1.0에 로그인이 없다. V2가 만든 뒤로 4단계부터 아무도 안 쓰는 유령이었다
drop table spring_session_attributes;
drop table spring_session;
